name: emba_thesis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.13
  - numpy
  - pandas
  - matplotlib
  - statsmodels
  - scikit-learn
  - holidays
  - ipykernel
  - openpyxl
  - pip
  - pip:
    - prophet
    - xgboost
    - torch
    - pyarrow
    - pmdarima